name: GCPoll
main: me.NinetyNine.poll.GCPoll
author: NinetyNine
version: 1.0
description: Do a quick poll!
commands:
  poll:
    usage: /<command>
    description: Interact with polls!
  gcpoll:
    usage: /<command>
    description: Creates polls!
permissions:
  poll.poll:
    description: Uses the poll command to do something with poll!
    default: true
  poll.admin:
    description: Edits, starts a poll!
    default: false